#!/usr/bin/env bash
# Install nginx that listens to port 80
# Get req using curl returns a page "Hello world"

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow "Nginx HTTP"

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
