#!/usr/bin/env bash
# Install nginx that listens to port 80
# Get req using curl returns a page "Hello world"

sudo apt-get update
sudo apt-get -y nginx

sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
