#!/usr/bin/env bash
# Install nginx that listens to port 80
# Get req using curl returns a page "Hello world"

sudo apt-get update
sudo apt-get -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
	listen	80 default_server;
	listen [::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
