#!/usr/bin/env bash
# Installs & configures HAproxy as required

sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt update
sudo apt install -y haproxy=1.8.\*

hgproxy_conf_file="/etc/haproxy/haproxy.cfg"

# Configure Load Balancer
fname="frontend http"
fbind="bind *:80"
fmode="mode http"
fdefault="default_backend web-backend"
frontend="$fname\n\t$fbind\n\t$fmode\n\t$fdefault\n"

bname="backend web-backend"
bbalance="balance roundrobin"
bserver1="server 448362-web-01 54.172.55.7:80 check"
bserver2="server 448362-web-02 54.157.151.17:80 check"
backend="$bname\n\t$bbalance\n\t$bserver1\n\t$bserver2"

sudo sed -i "$ a $frontend" $hgproxy_conf_file
sudo sed -i "$ a $backend" $hgproxy_conf_file

sudo service haproxy restart
