#!/usr/bin/env bash
# Installs & Configures HAproxy

sudo apt update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt update
sudo apt install -y haproxy=2.8.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend webwinter.tech
    timeout client  30000
    bind 0:80
    default_backend webwinter.tech_backend

backend webwinter.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 298443-web-01 54.90.41.29:80 check
    server 298443-web-02 54.88.199.223:80 check
EOT

sudo service haproxy restart
