#!/usr/bin/env bash
# Displays 1-100 where multiples of 3=Fizz, 5=Buzz, both=FizzBuzz

for (( i=1; i < 101; i++ ))
do
	if (( i % 15 == 0 )); then
		echo "FizzBuzz"
	elif ((i % 3 == 0 )); then
		echo "Fizz"
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
