#!/usr/bin/env bash
# Display hours from 0 to 12 & mins from 1-59 for 12hrs & 59mins

h=0
while [ "$h" -le 12 ]
do
	echo "Hour: $h"
	((h++))

	m=1
	while [ "$m" -le 59 ]
	do
		echo "$m"
		((m++))
	done
done
